export const SHIP_LABELS = [
  'FREIGHT SIG',
  'UNREGISTERED',
  'DRIVE TRACE',
  'GHOST SIG',
  'MINING VESSEL',
  'DEEP HAUL',
  'TRANSIT DRIVE',
  'DEBRIS HAULER',
  'COMMERCIAL',
  'UNIDENTIFIED',
  'RESEARCH',
  'MILITARY',
  'EXPLORATION',
  'SALVAGE',
  'TOWING',
  'PASSENGER',
  'FREIGHTER',
  'MINING',
  'HAULER',
  'SCIENTIFIC',
  'UNKNOWN',
];

export const SHIP_NAMES = [
  'ACHERON-2',
  'SABLE-WING',
  'STELLAROSA',
  'IKORA',
  'CETUS-3',
  'VESSEL YANTARA',
  'BRASK-ACTUAL',
  'STATION MINERVA',
  'OUTRIDER-7',
  'TRANSPORT-09',
  'MV HELION',
  'MV PALLOR',
  'DRIFT-3',
  'RELAY THETA',
  'SUPPLY-22',
  'TANKER-BRAVO',
  'THE LONG HAUL',
  'FERRY-14',
  'KASTOR',
  'MERIDIAN',
  'COLDFIRE',
  'VAGRANT III',
  'MV BELKA',
  'MV EREBUS',
  'TRANSIT-06',
  'HERALD-3',
  'MV JUNO',
  'ORION-7',
  'FLAB DRAGON',
  'ODINS BEARD',
  'BLACKBEARDS DELIGHTS',
];

export const STATION_NAMES = [
  'MINERVA',
  'SIRIX STATION',
  'TC NESTOR',
  'TC CYGNUS-4',
  'PL IRONSIDE',
  'WAYPOINT-9',
  'DEPOT-KAPPA',
  'MV LUCENT',
];
export const BEACON_NAMES = [
  `BEACON-${Math.floor(Math.random() * 10)}`,
  `BEACON-${Math.floor(Math.random() * 10)}`,
  `BEACON-${Math.floor(Math.random() * 10)}`,
  `DRONE-${Math.floor(Math.random() * 10)}`,
  `BEACON-${Math.floor(Math.random() * 10)}`,
  `BEACON-${Math.floor(Math.random() * 10)}`,
  `BEACON-${Math.floor(Math.random() * 10)}`,
  `BEACON-${Math.floor(Math.random() * 10)}`,
  `BEACON-${Math.floor(Math.random() * 10)}`,
  `BEACON-${Math.floor(Math.random() * 10)}`,
];
export const DISPATCHNAME = [
  'HARBOUR ADVISORY',
  'FLEET DISPATCH',
  'TRAFFIC CONTROL',
  'PORT AUTHORITY',
  'SAFETY DISPATCH',
  'EMERGENCY RESPONSE',
  'NAVAL DISPATCH',
  'CIVILIAN DISPATCH',
  'SECURITY DISPATCH',
  'RESCUE DISPATCH',
];
export const GHOST_FLEET_RADIUS = 40000000;
