import type { DockContact } from '../dockConfig';
import { INVENTORY_ITEMS } from '../inventoryCatalog';

export const CHEIA_DOOLHARDY: DockContact = {
  id: 'cheia-doolhardy',
  name: 'Cheia Doolhardy',
  role: 'quartermaster',
  age: 27,
  company: 'Entente Cordiale',
  portrait: '/profiles/cheia-doolhardy.jpg',
  bio: 'Quartermaster at Donington Station.',
  platform: 'REACH',
  inventory: {
    label: 'Mara Reeves',
    slots: [
      { itemId: INVENTORY_ITEMS.co2Filter.id, quantity: 3, capacity: 10, supply: 1, demand: 0 },
      {
        itemId: INVENTORY_ITEMS.hullRepairPatch.id,
        quantity: 6,
        capacity: 50,
        supply: 0.1,
        demand: 0.85,
      },
      { itemId: INVENTORY_ITEMS.commsBuffer.id, quantity: 1, capacity: 1, supply: 0, demand: 1 },
      {
        itemId: INVENTORY_ITEMS.emergencyBattery.id,
        quantity: 4,
        capacity: 8,
        supply: 1,
        demand: 0.1,
      },
    ],
  },
  dialogue: {
    id: 'cheia-doolhardy-quartermaster',
    openingTurnId: 'intro',
    turns: {
      intro: {
        id: 'trade-supplies',
        npcText: `Welcome to Donington. Your military requisition pass is in order, That gets you as much fuel, O2 power as you need and we have a few idle crew. We're having some banking issues, order from the top is no paper money, no radio transfers. So if you want anything else, all I can offer you is trade.`,
        audio: 'cheia-doolhardy.mp3',
        trade: {
          cargoBarter: true,
          acceptRatio: 1,
          insultRatio: 0.4,
          counterTargetRatio: 1.15,
          acceptThreshold: 44,
          insultThreshold: 12,
          counterMultiplier: 1.22,
          acceptPenaltyPerNegativeStance: 5,
          insultPenaltyPerNegativeStance: 2,
          insultReliefPerPositiveStance: 2,
          minimumInsultThreshold: 4,
          panelStatusOpen: 'Set both sides of the deal, then transmit.',
          panelStatusCleared: 'Offer cleared. Set a new package.',
          panelStatusEmptyOffer: 'Put goods on both sides — or at least what you are giving.',
          panelStatusInsult: 'Offer rejected as insulting.',
          panelStatusAccepted: 'They agree. Confirm to finalize the exchange.',
          panelStatusCounter: 'Counteroffer on the table: {offer}',
          panelStatusSuccess: 'Exchange complete: {offer}',
          panelStatusCounterDeclined: 'Counteroffer declined. Submit a new offer.',
          npcInsultText: 'Yu insulting us pilot. We can take wot we need',
          npcAcceptText: 'I can accept that. Confirm and we swap.',
          npcCounterText: 'Too light. I can do it for {offer}.',
          npcCompleteText: 'Transfer locked. We can trade again if you have more to move.',
          npcCounterDeclinedAckText: 'Then adjust your numbers and send again.',
          playerOfferText: 'Proposed deal: {offer}',
          playerAcceptText: 'Agreed. Executing exchange: {offer}',
          playerCounterAcceptText: 'Counter accepted. Executing: {offer}',
          playerCounterDeclineText: 'Counter declined. I will submit another offer.',
        },
        playerOptions: [
          {
            id: 'trade-back',
            label: `Got to go.`,
            text: `Got to go.`,
            nextTurnId: 'back-intro',
          },
        ],
      },
      'back-intro': {
        id: 'back-intro',
        npcText: `Come back anytime, this store's always open. `,
        trade: {
          cargoBarter: true,
          acceptRatio: 1,
          insultRatio: 0.4,
          counterTargetRatio: 1.15,
          acceptThreshold: 44,
          insultThreshold: 12,
          counterMultiplier: 1.22,
          acceptPenaltyPerNegativeStance: 5,
          insultPenaltyPerNegativeStance: 2,
          insultReliefPerPositiveStance: 2,
          minimumInsultThreshold: 4,
          panelStatusOpen: 'Set both sides of the deal, then transmit.',
          panelStatusCleared: 'Offer cleared. Set a new package.',
          panelStatusEmptyOffer: 'Put goods on both sides — or at least what you are giving.',
          panelStatusInsult: 'Offer rejected as insulting.',
          panelStatusAccepted: 'They agree. Confirm to finalize the exchange.',
          panelStatusCounter: 'Counteroffer on the table: {offer}',
          panelStatusSuccess: 'Exchange complete: {offer}',
          panelStatusCounterDeclined: 'Counteroffer declined. Submit a new offer.',
          npcInsultText: 'Yu insulting us pilot. We can take wot we need',
          npcAcceptText: 'I can accept that. Confirm and we swap.',
          npcCounterText: 'Too light. I can do it for {offer}.',
          npcCompleteText: 'Transfer locked. We can trade again if you have more to move.',
          npcCounterDeclinedAckText: 'Then adjust your numbers and send again.',
          playerOfferText: 'Proposed deal: {offer}',
          playerAcceptText: 'Agreed. Executing exchange: {offer}',
          playerCounterAcceptText: 'Counter accepted. Executing: {offer}',
          playerCounterDeclineText: 'Counter declined. I will submit another offer.',
        },
        playerOptions: [
          {
            id: 'trade-back',
            label: 'Back',
            text: `Got to go.`,
            nextTurnId: 'back-intro',
          },
        ],
      },
    },
  },
};
